name: Build application and runt tests
on: [push, workflow_dispatch]
jobs:
 build_and_run_tests:
   name: CI
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - name: Setup JDK
       uses: actions/setup-java@v2
       with:
        java-version: '17'
        distribution: 'adopt'
     - name: Build and run tests
       run: ./gradlew clean test

